# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cctv_pb2 as cctv__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cctv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitoringStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImage = channel.unary_unary(
                '/cctv.Monitoring/GetImage',
                request_serializer=cctv__pb2.Empty.SerializeToString,
                response_deserializer=cctv__pb2.Image.FromString,
                _registered_method=True)
        self.GetDetection = channel.unary_unary(
                '/cctv.Monitoring/GetDetection',
                request_serializer=cctv__pb2.Empty.SerializeToString,
                response_deserializer=cctv__pb2.Detection.FromString,
                _registered_method=True)
        self.GetCameraSettings = channel.unary_unary(
                '/cctv.Monitoring/GetCameraSettings',
                request_serializer=cctv__pb2.Empty.SerializeToString,
                response_deserializer=cctv__pb2.CameraSettings.FromString,
                _registered_method=True)
        self.SetCameraSettings = channel.unary_unary(
                '/cctv.Monitoring/SetCameraSettings',
                request_serializer=cctv__pb2.CameraSettings.SerializeToString,
                response_deserializer=cctv__pb2.Empty.FromString,
                _registered_method=True)


class MonitoringServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCameraSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCameraSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitoringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=cctv__pb2.Empty.FromString,
                    response_serializer=cctv__pb2.Image.SerializeToString,
            ),
            'GetDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetection,
                    request_deserializer=cctv__pb2.Empty.FromString,
                    response_serializer=cctv__pb2.Detection.SerializeToString,
            ),
            'GetCameraSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameraSettings,
                    request_deserializer=cctv__pb2.Empty.FromString,
                    response_serializer=cctv__pb2.CameraSettings.SerializeToString,
            ),
            'SetCameraSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCameraSettings,
                    request_deserializer=cctv__pb2.CameraSettings.FromString,
                    response_serializer=cctv__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cctv.Monitoring', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cctv.Monitoring', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Monitoring(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cctv.Monitoring/GetImage',
            cctv__pb2.Empty.SerializeToString,
            cctv__pb2.Image.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cctv.Monitoring/GetDetection',
            cctv__pb2.Empty.SerializeToString,
            cctv__pb2.Detection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCameraSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cctv.Monitoring/GetCameraSettings',
            cctv__pb2.Empty.SerializeToString,
            cctv__pb2.CameraSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCameraSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cctv.Monitoring/SetCameraSettings',
            cctv__pb2.CameraSettings.SerializeToString,
            cctv__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
